### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by Tungsteno74** [Jeremie-C/OrangePi.GPIO#1]
Hello @Jeremie-C 

```
root@OrangepiZero:/# pip list
Package       Version
------------- -------
OrangePi.GPIO 0.6.3
pip           18.0
setuptools    40.2.0
wheel         0.31.1
```
```
root@OrangepiZero:/# python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OPi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named OPi
>>> import OPi.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named OPi.GPIO
>>> import OPi.GPIO as GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named OPi.GPIO
```

I notice that i have only one file in the `OrangePi.GPIO` folder:
```
root@OrangepiZero:/# ls -a /usr/local/lib/python2.7/dist-packages/OPi
.  ..  GPIO.so
```

What's wrong?

Thanks

**Comment by Tungsteno74** [comment]
Well... i've reinstalled the module, rebooted the Zero... and now works! 
Strange thing but that's all.
